Login Page
hamasah-lab/hamlab pull request #37
Opened 2023-01-07 07:43 UTC by zeetec20

fix #23

2023-01-07 13:45 UTC, kalwabed requested changes

2023-01-07 13:45 UTC, kalwabed commented on app/(auth)/login/page.tsx
> +import Logo from 'src/assets/images/logo.png'
```suggestion
import Logo from '~/assets/images/logo.png'
```

2023-01-07 13:45 UTC, kalwabed commented on app/(auth)/login/page.tsx
> +      </Head>
Please use separate `head` files.

Reference: https://beta.nextjs.org/docs/api-reference/file-conventions/head

2023-01-07 13:45 UTC, kalwabed commented on app/(auth)/login/page.tsx
> +          }`}
Please use `clsxm()` from utils.

2023-01-07 13:45 UTC, kalwabed commented on src/components/form/label.tsx
> +  const propsMerge = { ...props, className }
Please use `clsxm` util to compose classnames.

2023-01-07 13:45 UTC, kalwabed commented on src/components/form/text-input.tsx
> +  const propsMerge = { ...props, className }
Please use `clsxm` util to compose classnames.

2023-01-07 13:45 UTC, kalwabed commented on tailwind.config.js
> +        'c-white-purple-2': '#e4e6fc',
Please be more verbose. Change `c` to `custom`.

2023-01-07 15:18 UTC, zeetec20 commented on app/(auth)/login/page.tsx
> +import Logo from 'src/assets/images/logo.png'
Waiting #42

2023-01-08 22:42 UTC, kalwabed requested changes

2023-01-08 22:42 UTC, kalwabed commented on src/components/ui/form/text-input.tsx
> +    'mt-2 bg-c-white-purple border border-c-white-purple-2 text-sm rounded-[4px] block w-full p-2.5 outline-none focus:border-c-light-purple text-c-black',
I think you forgot to change from `c` to `custom`, for example: `bg-c-white-purple`.

2023-01-08 22:42 UTC, kalwabed commented on src/components/ui/form/label.tsx
> +  const className = clsxm('text-xs text-c-black', props.className)
I think you forgot to change from `c` to `custom`.

2023-01-08 22:42 UTC, kalwabed commented on app/(auth)/login/page.tsx
> +    <div className="bg-c-white-broken flex min-h-screen w-screen flex-col items-center justify-center">
I think you forgot to change from `c` to `custom`

2023-01-11 09:50 UTC, kalwabed approved these changes
LGTM :100:

2023-01-11 09:50 UTC, merged